/*
虚线    虚线
虚线层    虚线
中心线层    点画线
中心线    CENTER2
0    Continuous
BZ    Continuous
双点划线    PHANTOM2
标注    Continuous
_坐标    Continuous
不打印    Continuous
参考点    Continuous
参考线    Continuous
图层1    Continuous
图层2    Continuous
尺寸线    Continuous
粗实线    Continuous
细实线    Continuous
隐藏层    Continuous
TEXT    Continuous
临时图形    Continuous
剖面线层    Continuous
图纸界限    Continuous
尺寸线层    Continuous
粗实线层    Continuous
细实线层    Continuous
BIAOZHU    Continuous
粗实线_粗加工    Continuous
Defpoints    Continuous
粗实线_非机械加工    Continuous
_MarkInformation    Continuous
*/
