/*
layer:虚线    虚线
layer:虚线层    虚线
layer:中心线层    点画线
layer:中心线    CENTER2
layer:0    Continuous
layer:BZ    Continuous
layer:双点划线    PHANTOM2
layer:标注    Continuous
layer:_坐标    Continuous
layer:不打印    Continuous
layer:参考点    Continuous
layer:参考线    Continuous
layer:图层1    Continuous
layer:图层2    Continuous
layer:尺寸线    Continuous
layer:粗实线    Continuous
layer:细实线    Continuous
layer:隐藏层    Continuous
layer:TEXT    Continuous
layer:临时图形    Continuous
layer:剖面线层    Continuous
layer:图纸界限    Continuous
layer:尺寸线层    Continuous
layer:粗实线层    Continuous
layer:细实线层    Continuous
layer:BIAOZHU    Continuous
layer:粗实线_粗加工    Continuous
layer:Defpoints    Continuous
layer:粗实线_非机械加工    Continuous
layer:_MarkInformation    Continuous
*/
